### ISSUE TITLE
Expose JsonSchema

### ISSUE THREAD

**Issue by L3Z4** [lateapexearlyspeed/Lateapexearlyspeed.JsonSchema#32]
Hello and thanks you for this amazing library.

I love the builder's ability to create JsonSchema. However, it seems that it's only possible to get a JsonValidator to validate a JSON. Is it possible to get the built JsonSchema? 
My aim is to expose it via an API so that the frontend can automatically generate a dynamic form. The JsonSchema structure should be a valid Json schema according to the specification https://json-schema.org/specification.

Thanks !

**Comment by lateapexearlyspeed** [comment]
Hi @L3Z4 Thanks for feedback.

Do you mean you want to be able to get that standard json schema "text" eventually after building JsonSchemaBuilder ?
Can I also understand more about your usecase about this? Previously this library focused on validation (from multiple possibilities to `JsonValidator`) but would happy to extend more functionalities.

**Comment by L3Z4** [comment]
Indeed I'd like to get the JsonSchema in "text" version to expose it via a REST Api.
Then I can use a frontend form generator like https://github.com/rjsf-team/react-jsonschema-form. Once the form is generated, the end-user should be able to fill it and I POST it to my REST Api.
Finally, I can use the initial JsonSchema to validate this model.

I cannot use C# classes to expose the model and deserialize it, because my model is dynamic.

I'm currently using https://github.com/gregsdennis/json-everything/tree/master/JsonSchema to do so, but it is quite challenging to extend the JsonSchema with custom attributes

**Comment by lateapexearlyspeed** [comment]
@L3Z4 Ok, I would plan to implement this direction (from JsonSchema back to json schema text), thanks for idea.
BTW, this library targets json schema spec - 2020.12 version, hope you are able to adopt this version.

**Comment by L3Z4** [comment]
Thanks you !
Adapting to latest spec version is not an issue for me.

**Comment by lateapexearlyspeed** [comment]
@L3Z4 the json schema output is supported in v1.1.4, document [here](https://github.com/lateapexearlyspeed/Lateapexearlyspeed.JsonSchema?tab=readme-ov-file#output-standard-json-schema-text-from-jsonvalidator), please try it, hope it can help.

**Comment by lateapexearlyspeed** [comment]
Hi @L3Z4  any issue you found after adopting new one ?

**Comment by lateapexearlyspeed** [comment]
Feel free to reopen if need, @L3Z4 .
