### ISSUE TITLE
multipleOf '0.001' for type 'number' did not work for all cases

### ISSUE THREAD

**Issue by axhero** [lateapexearlyspeed/Lateapexearlyspeed.JsonSchema#36]
Environment:
  - VS Version 17.10.1
  - .NET 8.0
  - <PackageReference Include="LateApexEarlySpeed.Json.Schema" Version="1.1.5" />

Description:

Schema:
....
              "PosMD": {
                "type": "number",
                "multipleOf": 0.001,
                "description": ""
              },
....

Number:
"PosMD":0.001 -> OK
"PosMD":114201340.720 -> OK
"PosMD":214201340.720 -> OK
"PosMD":314201340.720 -> FAILED
"PosMD": 8355604201340.72, -> FAILED  (original value)

Error JSON (Example):
{
  "InstanceLocation": [
    "Ruler",
    "Rulers",
    "0",
    "PosMD"
  ],
  "RelativeKeywordLocation": [
    "properties",
    "Ruler",
    "properties",
    "Rulers",
    "items",
    "properties",
    "PosMD",
    "multipleOf"
  ],
  "SchemaResourceBaseUri": "http://isravision.com/defect_schema.json",
  "SubSchemaRefFullUri": "http://isravision.com/defect_schema.json",
  "Keyword": "multipleOf",
  "ErrorMessage": "Instance: \u0027314201340,72\u0027 is not multiple of \u00270,001\u0027",
  "ResultCode": 1,
  "IsValid": false
}

Error Output:
FailedToMultiple: Instance: '314201340,72' is not multiple of '0,001' (Location: /Ruler/Rulers/0/PosMD)

**Comment by lateapexearlyspeed** [comment]
Hi @axhero this is fixed in LateApexEarlySpeed.Json.Schema v1.1.6, please try and feel free to reopen if need. 
Thanks for reporting this.
