### ISSUE TITLE
date-time format validation

### ISSUE THREAD

**Issue by bschwehn** [lateapexearlyspeed/Lateapexearlyspeed.JsonSchema#42]
For strings with format date-time, only a single fraction is allowed, but "2023-11-27T10:44:00.0000000+01:00" should be a valid string in format date-time (at least I think the JSON Schema does allow it, System.Text.Json parses it successfully also).

Presumably the "f" here: https://github.com/lateapexearlyspeed/Lateapexearlyspeed.JsonSchema/blob/master/LateApexEarlySpeed.Json.Schema/Keywords/DateTimeFormatValidator.cs#L12

should be "FFFFFFF" (7 uppercase F)

Additionally, it looks like it is currently not possible to override the format behaviour, trying to add a FormatValidator with FormatRegisty.AddFormatType for an existing format like "date-time" results in error

An item with the same key has already been added. Key: date-time

It would be nice if the internal formats could be customized also, is that currently possible somehow?

Thanks,
Ben

P.S.: an unrelated question: in https://github.com/lateapexearlyspeed/Lateapexearlyspeed.JsonSchema/wiki/Performance#-performance-tips you recommend to reuse an existing JsonValidator instance. Could you comment on if calling Validate() on a shared insance is thread safe?

**Comment by lateapexearlyspeed** [comment]
> it looks like it is currently not possible to override the format behaviour, trying to add a FormatValidator with FormatRegisty.AddFormatType for an existing format like "date-time" results in error

Yes, previously the decision is to be able to add custom FormatValidator but cannot update existing one. But I agree your requirement is valid, I will make it possible soon, thanks @bschwehn !

> if calling Validate() on a shared insance is thread safe?

Yes it is thread safe, I will update doc to indicate this, thanks.

**Comment by bschwehn** [comment]
Thanks, I think being able to override the format validators would be useful. I think technically RFC3399 does not limit the number of fractional seconds at all

> time-secfrac    = "." 1*DIGIT

My personal requirement is up to 7 fractional as this is the maximum precision when used as DateTimeOffset later on.

Alternatively, in line with https://json-schema.org/draft/2020-12/json-schema-validation#name-format-annotation-vocabular

> The implementation MUST provide options to enable and disable such evaluation and MUST be disabled by default

maybe being able to disable the build in format validation (but then still being able to add your own validations, including for the pre-defined formats, might be an option.

**Comment by lateapexearlyspeed** [comment]
> The implementation MUST provide options to enable and disable such evaluation and MUST be disabled by default

There is option to enable/disable format validation (JsonSchemaOptions.ValidateFormat) but its default value is 'enable' intentionally in this library, because I feel most users may have surprise when they found format keyword not work, considering most users may not notice this spec line :)

**Comment by bschwehn** [comment]
> There is option to enable/disable format validation (JsonSchemaOptions.ValidateFormat)

Oh, I somehow missed that, thanks

> but its default value is 'enable' intentionally in this library, because I feel most users may have surprise when they found format keyword not work, considering most users may not notice this spec line :)

Yes, I agree actually :)

**Comment by lateapexearlyspeed** [comment]
Added method 'SetFormatType()' in FormatRegistry in version 1.1.8 to be able to override existing format type.
For standard date-time format, I will investigate and improve internally later.
Please feel free to reopen if need, thanks @bschwehn  's feedback !

**Comment by lateapexearlyspeed** [comment]
@bschwehn FYI, standard 'date-time' format support is fixed in version 1.1.9.

**Comment by bschwehn** [comment]
Thank you, I can confirm this is working fine for me!
