### ISSUE TITLE
Reference to System.Text.Json V6.0.0 with vulnerable

### ISSUE THREAD

**Issue by ah1101** [lateapexearlyspeed/Lateapexearlyspeed.JsonSchema#48]
Version: 1.1.11
DotNet: 8.0

With the latest VS the vulnerable check with Nuget Package Manager is provided (or using `dotnet list xyz.sln package --vulnerable --include-transitive`). This shows that the assembly 'LateApexEarlySpeed.Json.Schema.dll' refer package 'System.Text.Json V6.0.0' with high severity, [see https://github.com/advisories/GHSA-8g4q-xg66-9fp4](https://github.com/advisories/GHSA-8g4q-xg66-9fp4).

If possible, change the creation of nuget package to
- update version of System.Text.Json assembly
- or remove fix reference System.* assembly to reuse underlying dotnet assembly

**Comment by lateapexearlyspeed** [comment]
1.1.12 is published.
