### ISSUE TITLE
Add method Validate(JsonDocument jdoc) and/or Validate(JsonNode jnode)

### ISSUE THREAD

**Issue by ah1101** [lateapexearlyspeed/Lateapexearlyspeed.JsonSchema#49]
Version: 1.1.11
DotNet Version: 8.0

The validation supports the method `Validate(string json)`. If an application already have dotnet objects, like JsonDocument or JsonNode, to handle JSON instances, it have to convert the object into string.

The should be avoid by providing overloads for Validate() method, like
- Validate(System.Text.Json.JsonDocument jdoc)
- and/or Validate(System.Text.Json.Nodes.JsonNode jnode)

(There are unfortunately two ways to handle JSON data in dotnet)

**Comment by lateapexearlyspeed** [comment]
Hi @ah1101 thanks, I will add mentioned overload `Validate(System.Text.Json.JsonDocument)`, please check if ok.

Current library implementation depends on standard `JsonElement` type for json instance during validation internally, so `JsonDocument` type is natural supporting type. Supporting it as parameter is not only easier to call, but also better for whole performance for `JsonDocument` user. 
However, it will need more effort to also implement validation against `JsonNode` type, so currently caller need to do convert for `JsonNode` parameter before call. (Even if simple convert is in library, the benefit will be only convenience, no performance gain)

New overload will be included in 1.1.12, additional feedback is welcome :)
