### ISSUE TITLE
Sign package to support "strong names"

### ISSUE THREAD

**Issue by ah1101** [lateapexearlyspeed/Lateapexearlyspeed.JsonSchema#50]
Version: 1.1.11
Dotnet Version: 8.0

We are using signed assemblies. Including the validator package returns the following warning during build
`warning CS8002: Referenced assembly 'LateApexEarlySpeed.Json.Schema, Version=1.1.11.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`

Please, sign the package to support strong names.

**Comment by lateapexearlyspeed** [comment]
Hi @ah1101 thanks, signed package will be included in 1.1.12.

**Comment by lateapexearlyspeed** [comment]
1.1.12 is published.
